# Generated by Django 4.2.3 on 2023-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
